import {chromium} from 'playwright';
import {mkdirSync,writeFileSync} from 'node:fs';
const url=process.env.QA_URL||'http://127.0.0.1:8081/';
const output=process.env.QA_OUT||'/workspace/screenshots';mkdirSync(output,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const report={checks:[],pageErrors:[],failedRequests:[]};
const check=(condition,name,detail)=>{report.checks.push({name,passed:!!condition,...(detail===undefined?{}:{detail})});if(!condition)throw Error(name);};
try {
 const page=await browser.newPage({viewport:{width:1440,height:900}});
 page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('requestfailed',r=>report.failedRequests.push({url:r.url(),error:r.failure()?.errorText}));
 await page.addInitScript(()=>{window.__drawCount=0;window.__triangles=0;for(const p of [WebGLRenderingContext.prototype,WebGL2RenderingContext.prototype])for(const key of ['drawElements','drawArrays','drawElementsInstanced','drawArraysInstanced']){const fn=p[key];if(fn)p[key]=function(...args){window.__drawCount++;if(args[0]===4)window.__triangles+=(key.includes('Elements')?args[1]:args[2])/3;return fn.apply(this,args);};}});
 await page.goto(url,{waitUntil:'domcontentloaded'});await page.waitForTimeout(1500);await page.evaluate(()=>document.fonts.ready);
 check(await page.locator('h1').innerText()==='R. UMANGA','Hero renders');
 check(await page.locator('canvas').count()===0,'3D is not loaded at the opening');
 check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Desktop has no horizontal page overflow');
 await page.screenshot({path:output+'/studio-desktop.png'});
 await page.locator('#photography').evaluate(el=>el.scrollIntoView({behavior:'instant'}));await page.waitForTimeout(400);
 await page.screenshot({path:output+'/studio-album.png'});
 const strip=page.locator('.book-track');await strip.scrollIntoViewIfNeeded();const box=await strip.boundingBox();
 await page.mouse.move(box.x+box.width*.5,Math.min(850,box.y+box.height*.5));
 const yBefore=await page.evaluate(()=>scrollY);await page.mouse.wheel(0,420);await page.waitForTimeout(300);
 check(await strip.evaluate(el=>el.scrollLeft)>100,'Wheel over album moves photographs');
 check(Math.abs(await page.evaluate(()=>scrollY)-yBefore)<2,'Wheel over album keeps page stationary');
 await page.mouse.move(15,150);await page.mouse.wheel(0,220);await page.waitForTimeout(350);
 check(await page.evaluate(()=>scrollY)>yBefore+50,'Wheel outside album scrolls page');
 await strip.evaluate(el=>{el.scrollLeft=el.scrollWidth;el.scrollIntoView({block:'center',behavior:'instant'});});
 const endBox=await strip.boundingBox();await page.mouse.move(endBox.x+endBox.width*.5,Math.min(850,endBox.y+endBox.height*.5));const edgeY=await page.evaluate(()=>scrollY);await page.mouse.wheel(0,200);await page.waitForTimeout(300);
 check(await page.evaluate(()=>scrollY)>edgeY,'Album end releases scrolling');
 await page.getByRole('button',{name:'Street',exact:true}).click();check(await page.locator('.book-frame').count()===2,'Photo filters work');
 await page.getByRole('button',{name:'Open Durbar at Dusk'}).click();check(await page.getByRole('dialog').isVisible(),'Photo opens in dialog');await page.keyboard.press('ArrowRight');check(await page.locator('.dialog-caption h3').innerText()==='Evening Crowd','Lightbox keyboard navigation works');await page.keyboard.press('Escape');check(await page.getByRole('dialog').count()===0,'Escape closes lightbox');
 check(await page.getByRole('button',{name:'Open Durbar at Dusk'}).evaluate(el=>el===document.activeElement),'Lightbox restores focus');
 await page.getByRole('button',{name:'All',exact:true}).click();
 await page.evaluate(()=>window.scrollTo({top:document.querySelector('#camera').getBoundingClientRect().top+scrollY,behavior:'instant'}));
 await page.locator('canvas').waitFor({state:'visible'});await page.waitForTimeout(1400);
 check(await page.evaluate(()=>window.__drawCount)>0,'WebGL camera produces rendered draw calls');
 await page.screenshot({path:output+'/studio-camera.png'});
 const idle=await page.evaluate(()=>window.__drawCount);await page.waitForTimeout(500);check(await page.evaluate(()=>window.__drawCount)===idle,'Camera makes zero additional draw calls when idle',{drawCallsBefore:idle,drawCallsAfter:await page.evaluate(()=>window.__drawCount)});
 await page.evaluate(()=>window.scrollBy({top:230,behavior:'instant'}));await page.waitForTimeout(700);const moving=await page.evaluate(()=>window.__drawCount);check(moving>idle,'Camera redraws on section scroll',{additionalDrawCalls:moving-idle});
 await page.screenshot({path:output+'/studio-camera-rotated.png'});await page.waitForTimeout(500);const settled=await page.evaluate(()=>window.__drawCount);await page.waitForTimeout(500);check(await page.evaluate(()=>window.__drawCount)===settled,'Camera stops drawing after scroll settles');
 await page.mouse.move(400,400);await page.mouse.down();await page.mouse.move(700,500,{steps:8});await page.mouse.up();await page.waitForTimeout(200);check(await page.evaluate(()=>window.__drawCount)===settled,'Pointer dragging does not rotate camera');
 await page.locator('#journey').evaluate(el=>el.scrollIntoView({behavior:'instant'}));await page.mouse.move(0,0);await page.waitForTimeout(400);const t1=await page.locator('.journey-belt').evaluate(el=>getComputedStyle(el).transform);await page.waitForTimeout(400);const t2=await page.locator('.journey-belt').evaluate(el=>getComputedStyle(el).transform);check(t1!==t2,'Creative journey moves automatically');
 await page.getByRole('button',{name:'Pause creative journey'}).click();await page.waitForTimeout(100);check(await page.locator('.journey-belt').evaluate(el=>getComputedStyle(el).animationPlayState)==='paused','Journey enters paused state');const pause1=await page.locator('.journey-belt').evaluate(el=>getComputedStyle(el).transform);await page.waitForTimeout(400);check(pause1===await page.locator('.journey-belt').evaluate(el=>getComputedStyle(el).transform),'Journey pause works');
 await page.screenshot({path:output+'/studio-journey.png'});
 const offscreen=await page.evaluate(()=>window.__drawCount);await page.waitForTimeout(400);check(await page.evaluate(()=>window.__drawCount)===offscreen,'Camera remains idle off screen');
 await page.locator('.grade-range').focus();const original=await page.locator('.grade-range').inputValue();await page.keyboard.press('ArrowRight');check(Number(await page.locator('.grade-range').inputValue())===Number(original)+1,'Color comparison supports keyboard');
 await page.locator('#about').evaluate(el=>el.scrollIntoView({behavior:'instant'}));await page.waitForTimeout(700);await page.screenshot({path:output+'/studio-about.png'});
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(450);check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile has no horizontal page overflow');await page.screenshot({path:output+'/studio-mobile.png'});
 await page.getByRole('button',{name:'Open menu'}).click();check(await page.getByRole('dialog').isVisible(),'Mobile menu opens');await page.getByRole('dialog').getByRole('link',{name:'About'}).click();check(await page.getByRole('dialog').count()===0,'Mobile menu closes after navigation');
 await page.evaluate(()=>window.scrollTo({top:document.querySelector('#camera').getBoundingClientRect().top+scrollY,behavior:'instant'}));await page.waitForTimeout(1000);await page.screenshot({path:output+'/studio-camera-mobile.png'});check(await page.locator('canvas').isVisible(),'Mobile camera remains visible');
 await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#journey').evaluate(el=>el.scrollIntoView({behavior:'instant'}));check(await page.locator('.journey-belt').evaluate(el=>getComputedStyle(el).animationName)==='none','Reduced motion stops automatic journey');
 await page.evaluate(()=>Promise.all([...document.images].map(img=>img.decode().catch(()=>null))));check(await page.evaluate(()=>[...document.images].every(img=>img.naturalWidth>0)),'All page images load');
 check(report.pageErrors.length===0,'No uncaught application errors',report.pageErrors);
} catch(error){report.failure=error.message;process.exitCode=1;} finally {await browser.close();writeFileSync(output+'/studio-qa.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}
